-- 
-- Table structure for table `logs`
-- 

CREATE TABLE `logs` (
  `id` int(10) NOT NULL auto_increment,
  `Year` int(4) NOT NULL default '0',
  `Quarter` int(1) NOT NULL default '0',
  `Month` int(4) NOT NULL default '0',
  `DayOfMonth` int(4) NOT NULL default '0',
  `DayOfWeek` int(4) NOT NULL default '0',
  `FlightDate` date default '0000-00-00',
  `UniqueCarrier` varchar(8) NOT NULL,
  `AirlineID` int(4) NOT NULL default '0',
  `Carrier` varchar(8) NOT NULL,
  `TailNum` varchar(8) default NULL,
  `FlightNum` int(4) NOT NULL default '0',
  `Origin` varchar(8) NOT NULL,
  `OriginCityName` varchar(64) NOT NULL,
  `OriginState` varchar(2) NOT NULL,
  `OriginWac` int(4) NOT NULL default '0',
  `Dest` varchar(8) NOT NULL,
  `DestCityName` varchar(64) NOT NULL,
  `DestState` varchar(2) NOT NULL,
  `DestWac` int(4) NOT NULL default '0',
  `CRSDepTime` varchar(4) NOT NULL default '0000',
  `DepTime` varchar(4) NOT NULL default '0000',
  `DepDelay` int(4) NOT NULL default '0',
  `DepDelayMinutes` int(4) NOT NULL default '0',
  `DepDel15` int(1) NOT NULL default '0',
  `DepartureDelayGroups` int(4) NOT NULL default '0',
  `DepTimeBlk` varchar(9) NOT NULL,
  `TaxiOut` int(4) NOT NULL default '0',
  `WheelsOff` varchar(4) NOT NULL default '0000',
  `WheelsOn` varchar(4) NOT NULL default '0000',
  `TaxiIn` int(4) NOT NULL default '0',
  `CRSArrTime` varchar(4) NOT NULL default '0000',
  `ArrTime` varchar(4) NOT NULL default '0000',
  `ArrDelay` int(4) NOT NULL default '0',
  `ArrDelayMinutes` int(4) NOT NULL default '0',
  `ArrDel15` int(1) NOT NULL default '0',
  `ArrivalDelayGroups` int(4) NOT NULL default '0',
  `ArrTimeBlk` varchar(9) NOT NULL,
  `Cancelled` int(1) NOT NULL default '0',
  `CancellationCode` varchar(1) NOT NULL,
  `Diverted` int(1) NOT NULL default '0',
  `CRSElapsedTime` int(4) NOT NULL default '0',
  `ActualElapsedTime` int(4) NOT NULL default '0',
  `AirTime` int(4) NOT NULL default '0',
  `Flights` int(4) NOT NULL default '0',
  `Distance` int(4) NOT NULL default '0',
  `DistanceGroup` int(4) NOT NULL default '0',
  `CarrierDelay` int(4) NOT NULL default '0',
  `WeatherDelay` int(4) NOT NULL default '0',
  `NASDelay` int(4) NOT NULL default '0',
  `SecurityDelay` int(4) NOT NULL default '0',
  `LateAircraftDelay` int(4) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `uniquecarrier` (`UniqueCarrier`),
  KEY `origin_dest_dayofweek` (`Origin`,`Dest`,`DayOfWeek`)
) ENGINE=MyISAM AUTO_INCREMENT=537794 DEFAULT CHARSET=latin1;
